name: Docker Image CI

on: 
  push:
    branches: 
      - master

jobs:

  build:
 
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        cd src/DevAdventCalendarCompetition 
        docker build . --file Dockerfile --tag docker.pkg.github.com/cloudadventcalendar/devadventcalendar/app:2020
    - name: Push the Docker image
      run: |
        echo "${{ github.token }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
        docker push docker.pkg.github.com/cloudadventcalendar/devadventcalendar/app:2020
